#!/bin/sh

VENV_DIR="$1"
ARCH="$2"
TEST_DIR="$3"
RESULTS_DIR="$4"

mkdir -p "$RESULTS_DIR"

# Controls the output generated by Avocado when running tests.
# Any number of command separated loggers are accepted.  For more
# information please refer to "avocado --help".
AVOCADO_SHOW=app

"$VENV_DIR/bin/python" \
    -m avocado \
    --show="$AVOCADO_SHOW" run \
    --job-results-dir="$RESULTS_DIR" \
    --filter-by-tags-include-empty \
    --filter-by-tags-include-empty-key \
    -t "arch:$ARCH" \
    --tap - \
    "$TEST_DIR"
