QAPI_TARGET_MODULES = machine-target misc-target

obj-y = qapi-introspect.o
obj-y += $(QAPI_TARGET_MODULES:%=qapi-types-%.o)
obj-y += qapi-types.o
obj-y += $(QAPI_TARGET_MODULES:%=qapi-visit-%.o)
obj-y += qapi-visit.o
obj-y += $(QAPI_TARGET_MODULES:%=qapi-events-%.o)
obj-y += qapi-events.o
obj-y += $(QAPI_TARGET_MODULES:%=qapi-commands-%.o)
obj-y += qapi-commands.o
